/* This file was generated by ConfigHeader using the Zig Build System. */
// comments are preserved

// empty lines are preserved

#define VERSION_STR "1.2.3"

#define boolean_true /* comment after define is okay */

#undef boolean_false // same for line comment

#define uint_64 42

#define int_64 -42

#define string "meson"

#define ident meson

/* #undef not_defined */

#define is_defined
