; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -verify-machineinstrs < %s | FileCheck %s

target datalayout = "e-m:e-p:16:8-p1:8:8-i16:8-i32:8-i64:8-f32:8-f64:8-a:8-Fi8-n8"
target triple = "mos"

; Floating point comparisons are lowered to the GNU soft-float comparison
; libcalls (__ltsf2 etc.), which return a three-way -1/0/1 result.

define i1 @olt_f32(float %a, float %b) {
; CHECK-LABEL: olt_f32:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    jsr __ltsf2
; CHECK-NEXT:    lda __rc3
; CHECK-NEXT:    bpl .LBB0_2
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    lda #1
; CHECK-NEXT:    rts
; CHECK-NEXT:  .LBB0_2: ; %entry
; CHECK-NEXT:    lda #0
; CHECK-NEXT:    rts
entry:
  %r = fcmp olt float %a, %b
  ret i1 %r
}

define i1 @oeq_f32(float %a, float %b) {
; CHECK-LABEL: oeq_f32:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    jsr __eqsf2
; CHECK-NEXT:    ldy __rc3
; CHECK-NEXT:    bne .LBB1_5
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    ldy __rc2
; CHECK-NEXT:    bne .LBB1_5
; CHECK-NEXT:  ; %bb.2: ; %entry
; CHECK-NEXT:    cpx #0
; CHECK-NEXT:    bne .LBB1_5
; CHECK-NEXT:  ; %bb.3: ; %entry
; CHECK-NEXT:    tax
; CHECK-NEXT:    bne .LBB1_5
; CHECK-NEXT:  ; %bb.4: ; %entry
; CHECK-NEXT:    lda #1
; CHECK-NEXT:    rts
; CHECK-NEXT:  .LBB1_5: ; %entry
; CHECK-NEXT:    lda #0
; CHECK-NEXT:    rts
entry:
  %r = fcmp oeq float %a, %b
  ret i1 %r
}

define i1 @uno_f32(float %a, float %b) {
; CHECK-LABEL: uno_f32:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    jsr __unordsf2
; CHECK-NEXT:    ldy __rc3
; CHECK-NEXT:    bne .LBB2_5
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    ldy __rc2
; CHECK-NEXT:    bne .LBB2_5
; CHECK-NEXT:  ; %bb.2: ; %entry
; CHECK-NEXT:    cpx #0
; CHECK-NEXT:    bne .LBB2_5
; CHECK-NEXT:  ; %bb.3: ; %entry
; CHECK-NEXT:    tax
; CHECK-NEXT:    bne .LBB2_5
; CHECK-NEXT:  ; %bb.4: ; %entry
; CHECK-NEXT:    lda #0
; CHECK-NEXT:    rts
; CHECK-NEXT:  .LBB2_5: ; %entry
; CHECK-NEXT:    lda #1
; CHECK-NEXT:    rts
entry:
  %r = fcmp uno float %a, %b
  ret i1 %r
}

define i1 @one_f32(float %a, float %b) {
; CHECK-LABEL: one_f32:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    sta __rc16
; CHECK-NEXT:    lda __rc20
; CHECK-NEXT:    pha
; CHECK-NEXT:    lda __rc21
; CHECK-NEXT:    pha
; CHECK-NEXT:    lda __rc22
; CHECK-NEXT:    pha
; CHECK-NEXT:    lda __rc23
; CHECK-NEXT:    pha
; CHECK-NEXT:    lda __rc16
; CHECK-NEXT:    ldy __rc24
; CHECK-NEXT:    sty .Lone_f32_sstk ; 1-byte Folded Spill
; CHECK-NEXT:    ldy __rc25
; CHECK-NEXT:    sty .Lone_f32_sstk+1 ; 1-byte Folded Spill
; CHECK-NEXT:    ldy __rc26
; CHECK-NEXT:    sty .Lone_f32_sstk+2 ; 1-byte Folded Spill
; CHECK-NEXT:    ldy __rc27
; CHECK-NEXT:    sty .Lone_f32_sstk+3 ; 1-byte Folded Spill
; CHECK-NEXT:    ldy __rc28
; CHECK-NEXT:    sty .Lone_f32_sstk+4 ; 1-byte Folded Spill
; CHECK-NEXT:    sta __rc20
; CHECK-NEXT:    stx __rc21
; CHECK-NEXT:    ldy __rc2
; CHECK-NEXT:    sty __rc22
; CHECK-NEXT:    ldy __rc3
; CHECK-NEXT:    sty __rc23
; CHECK-NEXT:    ldy __rc4
; CHECK-NEXT:    sty __rc24
; CHECK-NEXT:    ldy __rc5
; CHECK-NEXT:    sty __rc25
; CHECK-NEXT:    ldy __rc6
; CHECK-NEXT:    sty __rc26
; CHECK-NEXT:    ldy __rc7
; CHECK-NEXT:    sty __rc27
; CHECK-NEXT:    jsr __gtsf2
; CHECK-NEXT:    tay
; CHECK-NEXT:    txa
; CHECK-NEXT:    cpy #1
; CHECK-NEXT:    sbc #0
; CHECK-NEXT:    lda __rc2
; CHECK-NEXT:    sbc #0
; CHECK-NEXT:    lda __rc3
; CHECK-NEXT:    sbc #0
; CHECK-NEXT:    bvc .LBB3_2
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    eor #128
; CHECK-NEXT:  .LBB3_2: ; %entry
; CHECK-NEXT:    tax
; CHECK-NEXT:    bpl .LBB3_4
; CHECK-NEXT:  ; %bb.3: ; %entry
; CHECK-NEXT:    ldx #0
; CHECK-NEXT:    jmp .LBB3_5
; CHECK-NEXT:  .LBB3_4: ; %entry
; CHECK-NEXT:    ldx #1
; CHECK-NEXT:  .LBB3_5: ; %entry
; CHECK-NEXT:    stx __rc28
; CHECK-NEXT:    ldx __rc22
; CHECK-NEXT:    stx __rc2
; CHECK-NEXT:    ldx __rc23
; CHECK-NEXT:    stx __rc3
; CHECK-NEXT:    ldx __rc24
; CHECK-NEXT:    stx __rc4
; CHECK-NEXT:    ldx __rc25
; CHECK-NEXT:    stx __rc5
; CHECK-NEXT:    ldx __rc26
; CHECK-NEXT:    stx __rc6
; CHECK-NEXT:    ldx __rc27
; CHECK-NEXT:    stx __rc7
; CHECK-NEXT:    ldx __rc21
; CHECK-NEXT:    lda __rc20
; CHECK-NEXT:    jsr __ltsf2
; CHECK-NEXT:    lda __rc3
; CHECK-NEXT:    bpl .LBB3_7
; CHECK-NEXT:  ; %bb.6: ; %entry
; CHECK-NEXT:    ldx #1
; CHECK-NEXT:    jmp .LBB3_8
; CHECK-NEXT:  .LBB3_7: ; %entry
; CHECK-NEXT:    ldx #0
; CHECK-NEXT:  .LBB3_8: ; %entry
; CHECK-NEXT:    stx __rc2
; CHECK-NEXT:    lda __rc28
; CHECK-NEXT:    ora __rc2
; CHECK-NEXT:    sta __rc16
; CHECK-NEXT:    ldx .Lone_f32_sstk+4 ; 1-byte Folded Reload
; CHECK-NEXT:    stx __rc28
; CHECK-NEXT:    ldx .Lone_f32_sstk+3 ; 1-byte Folded Reload
; CHECK-NEXT:    stx __rc27
; CHECK-NEXT:    ldx .Lone_f32_sstk+2 ; 1-byte Folded Reload
; CHECK-NEXT:    stx __rc26
; CHECK-NEXT:    ldx .Lone_f32_sstk+1 ; 1-byte Folded Reload
; CHECK-NEXT:    stx __rc25
; CHECK-NEXT:    ldx .Lone_f32_sstk ; 1-byte Folded Reload
; CHECK-NEXT:    stx __rc24
; CHECK-NEXT:    pla
; CHECK-NEXT:    sta __rc23
; CHECK-NEXT:    pla
; CHECK-NEXT:    sta __rc22
; CHECK-NEXT:    pla
; CHECK-NEXT:    sta __rc21
; CHECK-NEXT:    pla
; CHECK-NEXT:    sta __rc20
; CHECK-NEXT:    lda __rc16
; CHECK-NEXT:    rts
entry:
  %r = fcmp one float %a, %b
  ret i1 %r
}

define i1 @ueq_f32(float %a, float %b) {
; CHECK-LABEL: ueq_f32:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    sta __rc16
; CHECK-NEXT:    lda __rc20
; CHECK-NEXT:    pha
; CHECK-NEXT:    lda __rc21
; CHECK-NEXT:    pha
; CHECK-NEXT:    lda __rc22
; CHECK-NEXT:    pha
; CHECK-NEXT:    lda __rc23
; CHECK-NEXT:    pha
; CHECK-NEXT:    lda __rc16
; CHECK-NEXT:    ldy __rc24
; CHECK-NEXT:    sty .Lueq_f32_sstk ; 1-byte Folded Spill
; CHECK-NEXT:    ldy __rc25
; CHECK-NEXT:    sty .Lueq_f32_sstk+1 ; 1-byte Folded Spill
; CHECK-NEXT:    ldy __rc26
; CHECK-NEXT:    sty .Lueq_f32_sstk+2 ; 1-byte Folded Spill
; CHECK-NEXT:    ldy __rc27
; CHECK-NEXT:    sty .Lueq_f32_sstk+3 ; 1-byte Folded Spill
; CHECK-NEXT:    ldy __rc28
; CHECK-NEXT:    sty .Lueq_f32_sstk+4 ; 1-byte Folded Spill
; CHECK-NEXT:    sta __rc20
; CHECK-NEXT:    stx __rc21
; CHECK-NEXT:    ldy __rc2
; CHECK-NEXT:    sty __rc22
; CHECK-NEXT:    ldy __rc3
; CHECK-NEXT:    sty __rc23
; CHECK-NEXT:    ldy __rc4
; CHECK-NEXT:    sty __rc24
; CHECK-NEXT:    ldy __rc5
; CHECK-NEXT:    sty __rc25
; CHECK-NEXT:    ldy __rc6
; CHECK-NEXT:    sty __rc26
; CHECK-NEXT:    ldy __rc7
; CHECK-NEXT:    sty __rc27
; CHECK-NEXT:    jsr __eqsf2
; CHECK-NEXT:    ldy __rc3
; CHECK-NEXT:    bne .LBB4_5
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    ldy __rc2
; CHECK-NEXT:    bne .LBB4_5
; CHECK-NEXT:  ; %bb.2: ; %entry
; CHECK-NEXT:    cpx #0
; CHECK-NEXT:    bne .LBB4_5
; CHECK-NEXT:  ; %bb.3: ; %entry
; CHECK-NEXT:    tax
; CHECK-NEXT:    bne .LBB4_5
; CHECK-NEXT:  ; %bb.4: ; %entry
; CHECK-NEXT:    ldx #1
; CHECK-NEXT:    jmp .LBB4_6
; CHECK-NEXT:  .LBB4_5: ; %entry
; CHECK-NEXT:    ldx #0
; CHECK-NEXT:  .LBB4_6: ; %entry
; CHECK-NEXT:    stx __rc28
; CHECK-NEXT:    ldx __rc22
; CHECK-NEXT:    stx __rc2
; CHECK-NEXT:    ldx __rc23
; CHECK-NEXT:    stx __rc3
; CHECK-NEXT:    ldx __rc24
; CHECK-NEXT:    stx __rc4
; CHECK-NEXT:    ldx __rc25
; CHECK-NEXT:    stx __rc5
; CHECK-NEXT:    ldx __rc26
; CHECK-NEXT:    stx __rc6
; CHECK-NEXT:    ldx __rc27
; CHECK-NEXT:    stx __rc7
; CHECK-NEXT:    ldx __rc21
; CHECK-NEXT:    lda __rc20
; CHECK-NEXT:    jsr __unordsf2
; CHECK-NEXT:    ldy __rc3
; CHECK-NEXT:    bne .LBB4_12
; CHECK-NEXT:  ; %bb.7: ; %entry
; CHECK-NEXT:    ldy __rc2
; CHECK-NEXT:    bne .LBB4_12
; CHECK-NEXT:  ; %bb.8: ; %entry
; CHECK-NEXT:    cpx #0
; CHECK-NEXT:    bne .LBB4_12
; CHECK-NEXT:  ; %bb.9: ; %entry
; CHECK-NEXT:    tax
; CHECK-NEXT:    bne .LBB4_12
; CHECK-NEXT:  ; %bb.10: ; %entry
; CHECK-NEXT:    sec
; CHECK-NEXT:    lda #1
; CHECK-NEXT:    bcs .LBB4_13
; CHECK-NEXT:  .LBB4_11: ; %entry
; CHECK-NEXT:    sta __rc2
; CHECK-NEXT:    ldx __rc28
; CHECK-NEXT:    beq .LBB4_14
; CHECK-NEXT:    jmp .LBB4_15
; CHECK-NEXT:  .LBB4_12: ; %entry
; CHECK-NEXT:    clc
; CHECK-NEXT:    lda #1
; CHECK-NEXT:    bcc .LBB4_11
; CHECK-NEXT:  .LBB4_13: ; %entry
; CHECK-NEXT:    ldx #0
; CHECK-NEXT:    stx __rc2
; CHECK-NEXT:    ldx __rc28
; CHECK-NEXT:    bne .LBB4_15
; CHECK-NEXT:  .LBB4_14: ; %entry
; CHECK-NEXT:    lda #0
; CHECK-NEXT:  .LBB4_15: ; %entry
; CHECK-NEXT:    ora __rc2
; CHECK-NEXT:    sta __rc16
; CHECK-NEXT:    ldx .Lueq_f32_sstk+4 ; 1-byte Folded Reload
; CHECK-NEXT:    stx __rc28
; CHECK-NEXT:    ldx .Lueq_f32_sstk+3 ; 1-byte Folded Reload
; CHECK-NEXT:    stx __rc27
; CHECK-NEXT:    ldx .Lueq_f32_sstk+2 ; 1-byte Folded Reload
; CHECK-NEXT:    stx __rc26
; CHECK-NEXT:    ldx .Lueq_f32_sstk+1 ; 1-byte Folded Reload
; CHECK-NEXT:    stx __rc25
; CHECK-NEXT:    ldx .Lueq_f32_sstk ; 1-byte Folded Reload
; CHECK-NEXT:    stx __rc24
; CHECK-NEXT:    pla
; CHECK-NEXT:    sta __rc23
; CHECK-NEXT:    pla
; CHECK-NEXT:    sta __rc22
; CHECK-NEXT:    pla
; CHECK-NEXT:    sta __rc21
; CHECK-NEXT:    pla
; CHECK-NEXT:    sta __rc20
; CHECK-NEXT:    lda __rc16
; CHECK-NEXT:    rts
entry:
  %r = fcmp ueq float %a, %b
  ret i1 %r
}

define i1 @olt_f64(double %a, double %b) {
; CHECK-LABEL: olt_f64:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    jsr __ltdf2
; CHECK-NEXT:    lda __rc3
; CHECK-NEXT:    bpl .LBB5_2
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    lda #1
; CHECK-NEXT:    rts
; CHECK-NEXT:  .LBB5_2: ; %entry
; CHECK-NEXT:    lda #0
; CHECK-NEXT:    rts
entry:
  %r = fcmp olt double %a, %b
  ret i1 %r
}

define i1 @oeq_f64(double %a, double %b) {
; CHECK-LABEL: oeq_f64:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    jsr __eqdf2
; CHECK-NEXT:    ldy __rc3
; CHECK-NEXT:    bne .LBB6_5
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    ldy __rc2
; CHECK-NEXT:    bne .LBB6_5
; CHECK-NEXT:  ; %bb.2: ; %entry
; CHECK-NEXT:    cpx #0
; CHECK-NEXT:    bne .LBB6_5
; CHECK-NEXT:  ; %bb.3: ; %entry
; CHECK-NEXT:    tax
; CHECK-NEXT:    bne .LBB6_5
; CHECK-NEXT:  ; %bb.4: ; %entry
; CHECK-NEXT:    lda #1
; CHECK-NEXT:    rts
; CHECK-NEXT:  .LBB6_5: ; %entry
; CHECK-NEXT:    lda #0
; CHECK-NEXT:    rts
entry:
  %r = fcmp oeq double %a, %b
  ret i1 %r
}

define i1 @ugt_f64(double %a, double %b) {
; CHECK-LABEL: ugt_f64:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    jsr __ledf2
; CHECK-NEXT:    tay
; CHECK-NEXT:    txa
; CHECK-NEXT:    cpy #1
; CHECK-NEXT:    sbc #0
; CHECK-NEXT:    lda __rc2
; CHECK-NEXT:    sbc #0
; CHECK-NEXT:    lda __rc3
; CHECK-NEXT:    sbc #0
; CHECK-NEXT:    bvc .LBB7_2
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    eor #128
; CHECK-NEXT:  .LBB7_2: ; %entry
; CHECK-NEXT:    tax
; CHECK-NEXT:    bpl .LBB7_4
; CHECK-NEXT:  ; %bb.3: ; %entry
; CHECK-NEXT:    lda #0
; CHECK-NEXT:    rts
; CHECK-NEXT:  .LBB7_4: ; %entry
; CHECK-NEXT:    lda #1
; CHECK-NEXT:    rts
entry:
  %r = fcmp ugt double %a, %b
  ret i1 %r
}
