/* This file was generated by ConfigHeader using the Zig Build System. */
#ifndef CONFIG_H
#define CONFIG_H
/* #undef UNDEFINED */
#define DEFINED
#define TRUE 1
#define FALSE 0
#define ZERO 0
#define ONE 1
#define TEN 10
#define IDENT identifier
#define STRING "test"
#endif /* CONFIG_H */
