/* This file was generated by ConfigHeader using the Zig Build System. */
// cmakedefine with multi-word string value (truthy)
#define MULTI_WORD "hello world"

// cmakedefine with multi-word string value (falsy)
/* #undef MULTI_WORD_FALSE */

// cmakedefine with no replacement value (truthy)
#define NO_VALUE

// cmakedefine with no replacement value (falsy)
/* #undef NO_VALUE_FALSE */

// cmakedefine01 with underscored variable names (truthy)
#define WITH_UNDERSCORE_TRUE 1

// cmakedefine01 with underscored variable names (falsy)
#define WITH_UNDERSCORE_FALSE 0

// cmakedefine with leading/trailing underscores (truthy)
#define _LEADING 1
#define TRAILING_ 1

// cmakedefine01 with leading/trailing underscores (truthy)
#define _UNDER_01 1
#define UNDER_01_ 1

// cmakedefine with @ substitution in the replacement value (truthy)
#define SUBST_VAL text

// cmakedefine with @ substitution in the replacement value (falsy)
/* #undef SUBST_VAL_FALSE */

// cmakedefine with @ substitution as the variable name
#define ACTUAL_VAR custom_val

// cmakedefine with dollar-curly substitution as the variable name
#define ACTUAL_VAR custom_val

// @ and $ as literal config values
@
$
