/* This file was generated by ConfigHeader using the Zig Build System. */
// cmakedefine — value is null (undefined) → /* #undef */
/* #undef NOVAL */

// cmakedefine — value is true → #define ... 1
#define TRUEVAL 1

// cmakedefine — value is false → /* #undef */
/* #undef FALSEVAL */

// cmakedefine — value is 0 (falsy) → /* #undef */
/* #undef ZEROVAL */

// cmakedefine — value is 1 (truthy) → #define ... 1
#define ONEVAL 1

// cmakedefine — value is 10 (truthy) → #define ... 1
#define TENVAL 1

// cmakedefine — value is non-empty string (truthy) → #define ... 1
#define STRINGVAL 1

// cmakedefine — leading whitespace preserved in output
    #define STRINGVAL 1
	#define STRINGVAL 1


// cmakedefine01 — value is {} (defined, no value) → 0
#define BOOLNOVAL 0

// cmakedefine01 — value is true → 1
#define BOOLTRUEVAL 1

// cmakedefine01 — value is false → 0
#define BOOLFALSEVAL 0

// cmakedefine01 — value is 0 (falsy) → 0
#define BOOLZEROVAL 0

// cmakedefine01 — value is 1 (truthy) → 1
#define BOOLONEVAL 1

// cmakedefine01 — value is 10 (truthy) → 1
#define BOOLTENVAL 1

// cmakedefine01 — value is non-empty string (truthy) → 1
#define BOOLSTRINGVAL 1


// @-substitution — value is null → empty string
// 

// @-substitution — null values produce nothing even when packed
// 

// @-substitution — null values produce nothing even when separated
// .

// @-substitution — value is true → "1"
// 1

// @-substitution — value is false → "0"
// 0

// @-substitution — true + false packed → "10"
// 10

// @-substitution — false + true separated → "0.1"
// 0.1

// @-substitution — value is 0 → "0"
// 0

// @-substitution — value is 1 → "1"
// 1

// @-substitution — value is 10 → "10"
// 10

// @-substitution — 0 + 1 packed → "01"
// 01

// @-substitution — 0 + 10 separated → "0.10"
// 0.10

// @-substitution — value is string "test" → "test"
// test

// @-substitution — strings packed → "testtest"
// testtest

// @-substitution — strings separated → "test.test"
// test.test

// @-substitution — mixed null/string/true/zero → "test10"
// test10

// dollar-curly substitution — value is null → empty string
// 

// dollar-curly substitution — null values produce nothing even when packed
// 

// dollar-curly substitution — null values produce nothing even when separated
// .

// dollar-curly substitution — value is true → "1"
// 1

// dollar-curly substitution — value is false → "0"
// 0

// dollar-curly substitution — true + false packed → "10"
// 10

// dollar-curly substitution — false + true separated → "0.1"
// 0.1

// dollar-curly substitution — value is 0 → "0"
// 0

// dollar-curly substitution — value is 1 → "1"
// 1

// dollar-curly substitution — value is 10 → "10"
// 10

// dollar-curly substitution — 0 + 1 packed → "01"
// 01

// dollar-curly substitution — 0 + 10 separated → "0.10"
// 0.10

// dollar-curly substitution — value is string "test" → "test"
// test

// dollar-curly substitution — strings packed → "testtest"
// testtest

// dollar-curly substitution — strings separated → "test.test"
// test.test

// dollar-curly substitution — mixed null/string/true/zero → "test10"
// test10
