/* This file was generated by ConfigHeader using the Zig Build System. */
// empty lines are preserved

// double-wrapped at-sigils work like single-wrapped
@text@
@text@

// at-var lookup happens inside dollar-curly before dollar-curly lookup
text

// expanded variables are treated as strings and can be re-substituted
@STRING@
@STRING@
${STRING}
${STRING}
${STRING}
${STRING}
${text}
${text}
${text}

// nested dollar-curly expansion from the inside out
STRING
STRING

// nested dollar-curly — only completed brace blocks are expanded
NEST_UNDERSCORE_PROXY
NEST_UNDERSCORE_PROXY

// backslash is invalid in at-var names — preserved as literal
\@STRING\@

// backslash does not affect dollar-curly expansion
\text

// backslash before opening brace breaks dollar-curly identification
$\{STRING}

// bare at-sigils pass through unchanged with no variable map
#define AT @
#define ATAT @@
#define ATATAT @@@
#define ATATATAT @@@@
